import clamp from './clamp';
import distance from './distance';
import gaussian from './gaussian';
import manhattanDistance from './manhattanDistance';
import remap from './remap';
import sample from './sample';
import shuffle from './shuffle';
import sum from './sum';
import mean from './mean';
import stdDev from './stdDev';
declare const utils: {
    clamp: typeof clamp;
    distance: typeof distance;
    gaussian: typeof gaussian;
    manhattanDistance: typeof manhattanDistance;
    remap: typeof remap;
    sample: typeof sample;
    shuffle: typeof shuffle;
    sum: typeof sum;
    mean: typeof mean;
    stdDev: typeof stdDev;
};
export { utils };
